services:
  rag-app:
    build: .
    ports:
      - "8080:8080"
    container_name: rag_app

    environment:
      GeminiRoya: ${GeminiRoya}
    
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  